name: Version

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'v2026.3.31.0'

permissions:
  contents: write

jobs:
  zip:
    uses: BlazeSnow/ReleaseZip/.github/workflows/ReleaseZip.yml@main
    with:
      artifact_name: ${{ github.event.repository.name }}-${{ inputs.tag }}
      retention_days: 7

  publish:
    runs-on: ubuntu-latest
    needs: zip
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        lfs: true

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.tag }}
